from snakebids import bids, generate_inputs, get_wildcard_constraints

configfile: 'config/snakebids.yml'

# Global variables from the config file
bids_dir = config['bids_dir']
output_dir = config['output_dir']

inputs = generate_inputs(
    bids_dir=config["bids_dir"],
    pybids_inputs=config["pybids_inputs"],
    pybidsdb_dir=config.get("pybidsdb_dir"),
    pybidsdb_reset=config.get("pybidsdb_reset"),
    derivatives=config.get("derivatives", None),
    participant_label=config.get("participant_label", None),
    exclude_participant_label=config.get("exclude_participant_label", None),
    validate=not config.get("plugins.validator.skip", False)
)

# print("FUNC:", inputs['func'])
# print("DWI:", inputs['dwi'])

del inputs['t1w'].wildcards['run']

include: 'common.smk'
include: 'rules/structural.smk'
include: 'rules/dwi.smk'
include: 'rules/func.smk'
include: 'rules/mpc.smk'
include: 'rules/flair.smk'
include: 'rules/swm.smk'
include: 'rules/mpc_swm.smk'


rule all:
    input:
        # inputs['t1w'].expand(
        #     get_structural_outputs(inputs, output_dir)
        # ),
        # inputs['t1w'].expand(
        #     get_surf_outputs(inputs, output_dir)
        # ),
        # inputs['t1w'].expand(
        #     get_post_structural_outputs(inputs, output_dir)
        # ),
        # inputs['t1w'].expand(
        #     get_geodesic_distance_outputs(inputs, output_dir)
        # )
        # get_all_structural_outputs(inputs, output_dir)
        # inputs['func'].expand(
        #     get_func_outputs(inputs, output_dir)
        # )
        inputs['dwi'].expand(
            get_sc_outputs(inputs, output_dir)
        ),
        inputs["func"].expand(
            get_func_outputs(inputs, output_dir)
        ),
        inputs["t1w"].expand(
            get_mpc_outputs(inputs, output_dir)
        ),
        inputs["t1w"].expand(
            get_flair_outputs(inputs, output_dir)
        ),
        inputs["t1w"].expand(
            get_swm_outputs(inputs, output_dir)
        ),
        inputs["t1w"].expand(
            get_mpc_swm_outputs(inputs, output_dir)
        ),

